services:
  api:
    build:
      context: .
      target: dev
    env_file:
      - .env
    environment:
      STAGE: dev
      DATABASE_URL: postgresql://postgres:postgres@db:5432/reto_geest
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "pnpm prisma migrate deploy && pnpm run start:dev"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reto_geest
    ports:
      - '5432:5432'
    volumes:
      - db_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  db_dev_data:
